name: Contest Crawler

on:
  schedule:
    # 매일 오전 9시 (UTC 0시)에 실행
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행 가능
  push:
    branches: [ main ]

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run crawler
      run: |
        python src/main.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/contests.csv data/contests.json
        git diff --staged --quiet || git commit -m "Update contest data - $(date '+%Y-%m-%d %H:%M:%S')"
        git push